/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        border: "var(--border)",
        input: "var(--input)",
        ring: "var(--ring)",
        background: "var(--background)",
        foreground: "var(--foreground)",
        primary: {
          DEFAULT: "var(--primary)",
          foreground: "var(--primary-foreground)",
          50: "#ffe0f0",
          100: "#ffb3d6",
          200: "#ff80bb",
          300: "#ff4da0",
          400: "#ff1a85",
          500: "#ff0080",
          600: "#e6006b",
          700: "#cc0056",
          800: "#b30041",
          900: "#99002c",
          950: "#800017",
        },
        secondary: {
          DEFAULT: "var(--secondary)",
          foreground: "var(--secondary-foreground)",
        },
        destructive: {
          DEFAULT: "var(--destructive)",
          foreground: "var(--destructive-foreground)",
        },
        muted: {
          DEFAULT: "var(--muted)",
          foreground: "var(--muted-foreground)",
        },
        accent: {
          DEFAULT: "var(--accent)",
          foreground: "var(--accent-foreground)",
          50: "#ffffcc",
          100: "#ffff99",
          200: "#ffff66",
          300: "#ffff33",
          400: "#ffff00",
          500: "#e6e600",
          600: "#cccc00",
          700: "#b3b300",
          800: "#999900",
          900: "#808000",
        },
        popover: {
          DEFAULT: "var(--popover)",
          foreground: "var(--popover-foreground)",
        },
        card: {
          DEFAULT: "var(--card)",
          foreground: "var(--card-foreground)",
        },
        // Retro color palette
        "neon-pink": "var(--neon-pink)",
        "neon-cyan": "var(--neon-cyan)",
        "neon-green": "var(--neon-green)",
        "neon-yellow": "var(--neon-yellow)",
        "neon-purple": "var(--neon-purple)",
        "neon-orange": "var(--neon-orange)",
        "terminal-green": "var(--terminal-green)",
        "retro-blue": "var(--retro-blue)",
        "retro-dark": "var(--retro-dark)",
        "retro-darker": "var(--retro-darker)",
      },
      fontFamily: {
        'orbitron': ['Orbitron', 'monospace'],
        'tech': ['Share Tech Mono', 'monospace'],
        'vt323': ['VT323', 'monospace'],
        'mono': ['JetBrains Mono', 'monospace'],
      },
      borderRadius: {
        lg: "0px",
        md: "0px", 
        sm: "0px",
        none: "0px",
      },
      clipPath: {
        'retro-corner': 'polygon(8px 0, 100% 0, 100% calc(100% - 8px), calc(100% - 8px) 100%, 0 100%, 0 8px)',
        'retro-small': 'polygon(4px 0, 100% 0, 100% calc(100% - 4px), calc(100% - 4px) 100%, 0 100%, 0 4px)',
        'retro-large': 'polygon(12px 0, 100% 0, 100% calc(100% - 12px), calc(100% - 12px) 100%, 0 100%, 0 12px)',
      },
    },
  },
  plugins: [],
}; 